### PR TITLE
chore!: Remove "Translation" addon

### PR DESCRIPTION
**Pull request by igorDolzh**
https://linear.app/pleo/issue/HMS-1288/clean-ups-after-npm-package-for-translations-alive

This is clean up after moving to the solution using NPM packages for storing translations instead of having CDN for that.
Here I removed translation addon and everything that is associated with it.

I do have a question about testing it in the dev/staging env before pushing to prod.
On what env I may do that?

### CODE REVIEW

**Review by macko911 — APPROVED** [review]
Thank you for the clean up

**Comment by macko911** [comment]
We should ideally test this on the product-dev environment.
I've recently done a test using a pre-release [in bff-tools](https://github.com/pleo-io/bff-tools/releases/tag/terraform-module-v5.0.3-alpha) without having to merge the PR first. Are you familiar with how to test this without merging the PR? But merging the PR and testing the newly published version is ok with me too.

**Comment by igorDolzh** [comment]
> We should ideally test this on the product-dev environment. I've recently done a test using a pre-release [in bff-tools](https://github.com/pleo-io/bff-tools/releases/tag/terraform-module-v5.0.3-alpha) without having to merge the PR first. Are you familiar with how to test this without merging the PR? But merging the PR and testing the newly published version is ok with me too.

@macko911 Do you mean that when I merge this PR, the updates won't be in production automatically?
But anyway I'm for any possible testing (before or after merging) and I'm not familiar with `bff-tools` if you may share knowledge how to do that testing, it would be great!

**Comment by macko911** [comment]
> Do you mean that when I merge this PR, the updates won't be in production automatically?

Yes, you will then need to update terraform repo with the new version [here](https://github.com/pleo-io/terraform/blob/417d262e93cb4e054eaf27c8c205808854f0506a/components/product-web-v2/main.tf#L6). That change can then be deployed only to product-dev environment before merging.

But actually since this PR is marked as `chore` it probably won't trigger a new release, according to [the docs](https://github.com/googleapis/release-please?tab=readme-ov-file#step-1-ensure-releasable-units-are-merged). This can be fixed by changing the prefix to `chore!`, leading to a new major version.

**Pull request merged**
